### ISSUE TITLE
[bug] Issue title

### ISSUE THREAD

**Issue by Bug-Reaper** [kristerkari/pinar#27]
# 🐛 Bug report

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [ Y] I've searched open [issues](https://github.com/kristerkari/pinar/issues) to make sure I'm not opening a duplicate issue
- [ Y] I have read through the docs
- [ Y] I am using the latest version of Pinar

### Describe the Problem

onIndexChanged fires twice when custom function is setup.

**Expected behavior:** 
Expected the function to fire once per onPress

**Actual behavior:**
onIndexChanged fires multiple times for each actual navigation

Definition
![Screenshot_2019-04-01_23-14-49](https://user-images.githubusercontent.com/31227781/55380087-f5316b00-54d3-11e9-8288-a4a40c509c96.png)

Result of swiping or pressing the next button once
![Screenshot_2019-04-01_23-16-31](https://user-images.githubusercontent.com/31227781/55380156-31fd6200-54d4-11e9-9b86-e455db4157c1.png)

This is on Andriod FYI, will confirm it is the same on iOS if I test.

**Comment by Bug-Reaper** [comment]
Confirmed appears to be android only. I’ll take a quick stab at fixing it and make a PR if that’s cool

**Comment by kristerkari** [comment]
Thanks for reporting! Yeah the Anroid side might have some bugs. PRs are always welcome :)

**Comment by kristerkari** [comment]
I created a fix, but I need to get the example project updated to a newer version of React Native to properly test the fix.

**Comment by kristerkari** [comment]
I released v0.10.1 that should fix the bug.
