### ISSUE TITLE
[question] How can I jump to specified index?

### ISSUE THREAD

**Issue by codoffer** [kristerkari/pinar#32]
## 💬 Question

How can we jump to specified index of slide or page? scrollToPrev/scrollToNext is sliding next and previous. I want to jump to specific slide or page.

Can you help me regard this?

**Comment by kristerkari** [comment]
Hi @codoffer!

It would probably make sense to add a method that moves the carousel to a specific index.

There is the `scrollBy` method, but that works a bit differently.

**Comment by kristerkari** [comment]
I released v0.11.0 with a new `scrollToIndex` method:
https://github.com/kristerkari/pinar/releases/tag/0.11.0

**Comment by codoffer** [comment]
Hello @kristerkari , I have upgraded version of current package but not working. I have used below function to scroll. I am passing this.carousel as your example (ref of Carousel component)

`_handleImageClick = (imageIndex) => {
        this.carousel.scrollToIndex(imageIndex);
    }`

But its not working.

**Comment by kristerkari** [comment]
The problem with your code is that the `scrollToIndex` method takes an object as it's argument, not an index. The reason for it is that it will allow new options to be passed into the method in the future without breaking backwards compatibility.

This is how you should use it:

```js
this.carousel.scrollToIndex({ index: imageIndex });
```
