### ISSUE TITLE
[feature request] Merge the custom dot style instead of replacing the default

### ISSUE THREAD

**Issue by tomsotte** [kristerkari/pinar#37]
## ✨ Feature request

Instead of replacing the default dot style with the custom one I provide, I think a better strategy would be to merge the custom style with the default one.

https://github.com/kristerkari/pinar/blob/master/src/Pinar.tsx#L575-L579

## Motivation

This way I could retain some of the properties of the default style, like the spacing, size and form, while customising just what I need, like the backgroundColor for branding.
Also, most of the library I've used use the merging strategy for styles.

## Example

To branding the dot color without having to re-write the whole style (size, spacing, etc.) for it.

**Comment by kristerkari** [comment]
Thanks! makes sense

**Comment by kristerkari** [comment]
I released version 0.12.0 that has a new `mergeStyles` boolean property that implements this:
https://github.com/kristerkari/pinar/releases/tag/0.12.0
