### ISSUE TITLE
[feature request] allow overriding default styles

### ISSUE THREAD

**Issue by zanona** [kristerkari/pinar#42]
## ✨ Feature request

Allow overriding default styles

## Motivation

Whenever needing to tweak the `backgroundColor` of `slideDotActive`, for example. We need to declare all of its properties instead of only declaring one specific attribute. It would be nice if we could tweak specific properties whilst maintaining the defaults for others. 

One way of doing this would be also exporting `defaultStyles` publicly, so we can override it.

## Example

```tsx
import Carousel, {defaultStyles} from 'pinar';
<Carousel slideDotActive={{...defaultStyles.dotActive, backgroundColor: 'red'}}>
...
</Carousel>
```

Currently, the same can be achieved with `import {defaultStyles} from 'pinar/src/styles'` but I believe that the consumption would be easier if we could import that directly from the main package, so we don't rely on the internal structure of the package.

**Comment by kristerkari** [comment]
I released a new version 0.12.0 that allows `import Carousel, {defaultStyles} from 'pinar';`
https://github.com/kristerkari/pinar/releases/tag/0.12.0
