### ISSUE TITLE
Add onPress to each image

### ISSUE THREAD

**Issue by wealthyboy** [kristerkari/pinar#48]
How can i wrap the Images inside a TouchableHighlight so i use onPress event on each image . 

When i wrap the images inside  TouchableHighlight  the images does not show.

My code.

const images = [
  'https://nollyflix.tv/images/videos/cJ5am4MaVnipJR60ui26uB6K6PDVI3ZcsUng4QM7.jpeg',
  'https://nollyflix.tv/images/videos/50HVuLRANHfqzjTpu7o2abZkY85MlMtnjMdZBMkW.jpeg',
  'https://nollyflix.tv/images/videos/1kn18qkLBwTXFYML4KsbB5FIWehHQHnB8mjdjFKF.jpeg',
]

const deviceWidth = Dimensions.get('window').width

export default () => (
  <Carousel>
       {images.map((image, key) => {
          return (
            <TouchableHighlight onPress={() => console.log(true) }  key={`image${key}`}>
                <Image 
                  source={{uri: image}}
                  style={{ width: deviceWidth,flex: 1}}
                />
            </TouchableHighlight>
          );
        });
  </Carousel>
);

**Comment by fredojbg** [comment]
did you resolve this? @wealthyboy

**Comment by fredojbg** [comment]
i get the same problem

**Comment by kristerkari** [comment]
@wealthyboy @fredojbg  Sorry for the late answer. 

The reason why the images do not show up is that they need to be wrapped in a `<View>` component that is flexed to fill its container.

I added an example to the example app to show how to this can be done: https://github.com/kristerkari/pinar/commit/2d7942c694bef463184985f5f586bebc978b7e8a

What you need to do is something like this:

```tsx
    {images.map((image, key) => {
      /* eslint-disable react/no-array-index-key */
      return (
        <View
          style={{ flex: 1, alignItems: "center", justifyContent: "center" }}
          key={key}
        >
          <TouchableHighlight
            accessibilityRole="button"
            onPress={(): void => {
              Alert.alert(`Image ${key + 1} clicked`);
            }}
            style={{
              height: imageHeight,
              width: imageWidth,
            }}
          >
            <Image
              source={image}
              style={{
                flex: 1,
                height: imageHeight,
                width: imageWidth,
              }}
            />
          </TouchableHighlight>
        </View>
      );
    })}
```
