### ISSUE TITLE
[bug] Issue title

### ISSUE THREAD

**Issue by fungmo** [kristerkari/pinar#51]
# 🐛 Bug report
![image](https://user-images.githubusercontent.com/16655229/115212440-19039000-a133-11eb-9f38-d3d72be878a6.png)

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/kristerkari/pinar/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs
- [x] I am using the latest version of Pinar

### Describe the Problem

I tried to use expo install pinar, and an error was reported after the installation was successful.

### Environment

Run `npx envinfo --system --binaries --npmPackages pinar --markdown --clipboard`

```bash
## System:
 - OS: Windows 10 10.0.19042
 - CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
 - Memory: 9.27 GB / 15.95 GB
## Binaries:
 - Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - pinar: ^0.11.0 => 0.11.0

-------------------------------------------------------------------------

Expo CLI 4.4.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
        Build Tools: 23.0.3, 24.0.3, 25.0.3, 26.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.3, 31.0.0
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

**Comment by kristerkari** [comment]
Sorry, but this carousel component is for React Native only, it does not work in Web (in your screenshot Webpack is trying to load the library).
