### ISSUE TITLE
Why not React native swiper

### ISSUE THREAD

**Issue by crushy26** [kristerkari/pinar#72]
## 💬 Question

https://github.com/leecade/react-native-swiper

Is there any reason why this is separately made? RNS has been in existence for a long time.

Please let me know if there is any critical enhancement

**Comment by kristerkari** [comment]
@crushy26 Good question. 

Some of the things that come to mind:

- Pinar is fully tested with automated tests. It means that changes/fixed can be made easily and the existing functionality should be mostly bug free.
- Typescript is used by default.
-  Pinar supports accessibility, so Android TalkBack and iOS VoiceOver should be able to navigate the swiper/slider for people that need screen readers.

**Comment by crushy26** [comment]
Hey @kristerkari, thanks for responding, I am using it in production
